name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"

      - name: Lint codebase using golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --issues-exit-code=0 --timeout 5m

      - name: Run tests
        run: |
          go test ./...

      - name: Prepare release
        if: github.ref == 'refs/heads/main' && github.event.type != 'pull_request'
        uses: labd/changie-release-action@v0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-workflow: release.yaml
